[package]
name = "cotutelle-server"
description = "Serveur d'administration, API et DNS réseau local de Cotutelle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "cotutelle-server"
path = "src/main.rs"

[dependencies]
cotutelle-common.workspace = true
cotutelle-dns.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
axum.workspace = true
tower-http.workspace = true
sqlx.workspace = true
argon2.workspace = true
rand.workspace = true
sha2.workspace = true
hex.workspace = true
reqwest.workspace = true
futures-util.workspace = true
tar.workspace = true
flate2.workspace = true
